# Written By Paul Onyebuchi
# Title: controller.py
# Description: This program serves as the master controller
# for the hardware logs analyser automation pipeline.
# It looks for the compiled cpp program and automatically runs it,
# then parses the error_report.csv file and prints
# a clean user-friendly summary to the console.

from pathlib import Path
import sys
import subprocess
import csv

# Configuration & Constants
BASE_DIR = Path(__file__).resolve().parent

CPP_BINARY = BASE_DIR / "parser"
INPUT_FILE = BASE_DIR / "system_dump.txt" # This is the path to our cpp program
CSV_REPORT = BASE_DIR / "error_report.csv"

CRITICAL_THRESHOLD = 0  # This ensures we get an alert if any critical errors are found
ERROR_THRESHOLD = 4     # We get alerted if total errors exceed this number


# Function to the input log file 'system_dump.txt' exists
# =====================================
def prepare_input() -> bool:
    """
    This function verifies that the system log input file exists.
    """

    print(f"[Python] Checking input file: {INPUT_FILE.name}")

    if not INPUT_FILE.is_file():
        print(
            f"[Python ERROR] Input file '{INPUT_FILE.name}' "
            "was not found."
        )
        return False

    print("[Python] Input log found.")
    return True


# C++ Parser Execution
# =====================================
def run_cpp_parser() -> bool:
    """
    this function executes the compiled C++ parser and verifies its exit status.
    """

    print(f"[Python] Executing C++ parser: {CPP_BINARY.name}")

    if not CPP_BINARY.is_file():
        print(
            f"[Python ERROR] C++ parser '{CPP_BINARY.name}' "
            "does not exist."
        )
        return False

    if not CPP_BINARY.stat().st_mode & 0o111:
        print(
            f"[Python ERROR] C++ parser '{CPP_BINARY.name}' "
            "is not executable."
        )
        return False

    try:
        result = subprocess.run(
            [str(CPP_BINARY)],
            cwd=BASE_DIR,
            capture_output=True,
            text=True,
            check=False,
        )

    except OSError as exc:
        print(f"[Python ERROR] Failed to execute C++ parser: {exc}")
        return False

    if result.stdout:
        print(result.stdout.rstrip())

    if result.stderr:
        print(result.stderr.rstrip(), file=sys.stderr)

    if result.returncode != 0:
        print(
            f"[Python ERROR] C++ parser failed "
            f"with exit code {result.returncode}."
        )
        return False

    print("[Python] C++ parser completed successfully.")
    return True


# Function definition for analysing generated report from c++
def analyze_results() -> bool:
    """
    Read the CSV report generated by C++ and perform diagnostic analysis.
    """

    print(f"[Python] Reading report: {CSV_REPORT.name}")

    if not CSV_REPORT.is_file():
        print(
            f"[Python ERROR] Expected report '{CSV_REPORT.name}' "
            "was not generated."
        )
        return False

    required_columns = {"Log_Level", "Count"}

    total_faults = 0
    critical_alerts = 0

    try:
        with CSV_REPORT.open(
            mode="r",
            encoding="utf-8",
            newline=""
        ) as file:

            csv_reader = csv.DictReader(file)

            if csv_reader.fieldnames is None:
                print("[Python ERROR] CSV report is empty.")
                return False

            missing_columns = required_columns - set(csv_reader.fieldnames)

            if missing_columns:
                print(
                    "[Python ERROR] CSV report is missing required "
                    f"columns: {', '.join(sorted(missing_columns))}"
                )
                return False

            print("\n" + "=" * 45)
            print("          SYSTEM DIAGNOSTIC REPORT")
            print("=" * 45)

            for line_number, row in enumerate(csv_reader, start=2):
                try:
                    log_level = row["Log_Level"].strip()
                    count = int(row["Count"])

                except (KeyError, TypeError, ValueError) as exc:
                    print(
                        f"[Python ERROR] Invalid CSV data on "
                        f"line {line_number}: {exc}"
                    )
                    return False

                if count < 0:
                    print(
                        f"[Python ERROR] Negative occurrence count "
                        f"on line {line_number}."
                    )
                    return False

                total_faults += count

                print(
                    f" -> {log_level:<10}: "
                    f"{count} occurrences"
                )

                if (
                    log_level == "CRITICAL"
                    and count > CRITICAL_THRESHOLD
                ):
                    critical_alerts += count

    except OSError as exc:
        print(
            f"[Python ERROR] Unable to read report "
            f"'{CSV_REPORT.name}': {exc}"
        )
        return False

    print("=" * 45)
    print(f"Total Logged Faults: {total_faults}")
    print("=" * 45)

    # Diagnostic evaluation
    if critical_alerts > 0:
        print(
            "🚨 [ALERT] CRITICAL system errors detected. "
            "Immediate investigation required."
        )

    elif total_faults > TOTAL_FAULT_THRESHOLD:
        print(
            "⚠️ [WARNING] Total system fault threshold exceeded. "
            "Review system logs."
        )

    else:
        print(
            "✅ [PASS] System diagnostic parameters are "
            "within acceptable operational limits."
        )

    print("=" * 45)

    return True

# Main application pipeline
#===========================
def main() -> int:
    """
    Main function to complete system log analysis pipeline.

    Exit codes:
        0 = Pipeline completed successfully.
        1 =Input preparation failed.
        2 = C++ parser failed
        3 = Report Analysis failed.
    """

    print("=" * 60)
    print("[Python] System log analyser pipeline started.")
    print("=" * 60)

    # 1.) Verify input
    if not prepare_input():
        print("[Python] Pipeline aborted.")
        return 1

    # 2.) Execute c++ parser
    if not run_cpp_parser():
        print("[Python] Pipeline aborted due to C++ parser failure.")
        return 2

    # 3.) Analyse the generated report from c++
    if not analyze_results():
        print("[Python] Pipeline aborted during report analysis.")
        return 3

    print("[Python] System Log Analyzer pipeline completed successfully.")

    return 0

# Application entry point

if __name__ == "__main__":
    raise SystemExit(main())


